### ISSUE TITLE
Git lens current line blame not working in the new VS Code insiders Version

### ISSUE THREAD

**Issue by prasanthnv** [eamodio/vscode-gitlens#656]
Issue Type: <b>Bug</b>

Git lense current line blame not showing up !

Extension version: 9.5.1
VS Code version: Code - Insiders 1.32.0-insider (a509265116babc17648c9052eeeb8ae2909fed87, 2019-02-13T06:14:01.838Z)
OS version: Linux x64 4.15.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4094)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.55GB (1.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@prasanthnv Hrm, I'm not seeing any issue in the latest insiders. Can you try re-installing GitLens? If you are still having an issue, can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by metra** [comment]
Strangely enough, just setting the `outputLevel` to `debug` fixed the issue for me.

**Comment by Guria** [comment]
I still can't enable current line blame annotations on VSCode 1.31.1:
```
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

Here is debug output:
```
[2019-02-27 10:29:17:035] [1] GitService.initialize
[2019-02-27 10:29:17:229] Git found: 2.20.1.windows.1 @ C:\Users\Alexey Gurianov\scoop\shims\git.exe • 78 ms
[2019-02-27 10:29:17:229] [1] GitService.initialize completed • 194 ms
[2019-02-27 10:29:17:230] Starting repository search in 1 folders
[2019-02-27 10:29:17:230] Searching for repositories (depth=1) in 'c:\ws\bookedby-react-ui-mobile' ...
[2019-02-27 10:29:17:236] [2] GitUri.fromUri — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx)
[2019-02-27 10:29:17:236] [3] GitService.getRepoPath — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx)
[2019-02-27 10:29:17:236] [4] GitService.getRepository — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx), t={"skipCacheUpdate":true}
[2019-02-27 10:29:17:240] GitLens(v9.5.1) activated • 332 ms
[2019-02-27 10:29:17:301] [5] GitService.getOrderedRepositories
[2019-02-27 10:29:17:301] [6] GitService.getRepositories
[2019-02-27 10:29:17:306] [c:\ws\bookedby-react-ui-mobile] git rev-parse --show-toplevel • 76 ms 
[2019-02-27 10:29:17:307] Repository found in 'c:/ws/bookedby-react-ui-mobile'
[2019-02-27 10:29:17:315] Completed repository search (depth=1) in 'c:\ws\bookedby-react-ui-mobile' • 84 ms
[2019-02-27 10:29:17:411] [c:/ws/bookedby-react-ui-mobile] git remote -v • 71 ms 
[2019-02-27 10:29:17:415] [6] GitService.getRepositories completed • 114 ms
[2019-02-27 10:29:17:415] [5] GitService.getOrderedRepositories completed • 114 ms
[2019-02-27 10:29:17:416] [8] GitService.getStatusForRepo — e=c:/ws/bookedby-react-ui-mobile
[2019-02-27 10:29:17:484] [c:/ws/bookedby-react-ui-mobile] git ls-files -- src/Modals/DDatePicker/index.tsx • 71 ms 
[2019-02-27 10:29:17:484] [7] GitService.isTracked returned true • 72 ms — e=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx, t=c:/ws/bookedby-react-ui-mobile, i={"skipCacheUpdate":true}
[2019-02-27 10:29:17:484] [4] GitService.getRepository returned c:/ws/bookedby-react-ui-mobile • 247 ms
[2019-02-27 10:29:17:484] [3] GitService.getRepoPath returned c:/ws/bookedby-react-ui-mobile • 248 ms
[2019-02-27 10:29:17:484] [2] GitUri.fromUri returned GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile) • 248 ms
[2019-02-27 10:29:17:484] [9] GitService.getRepository — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:17:484] [9] GitService.getRepository returned c:/ws/bookedby-react-ui-mobile • 0 ms
[2019-02-27 10:29:17:534] [c:/ws/bookedby-react-ui-mobile] git status --porcelain=v2 --branch -u • 118 ms 
[2019-02-27 10:29:17:534] [8] GitService.getStatusForRepo completed • 118 ms
[2019-02-27 10:29:17:534] [b] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription
[2019-02-27 10:29:17:535] [c] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).subscribe
[2019-02-27 10:29:17:535] [c] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).subscribe completed • 0 ms
[2019-02-27 10:29:17:535] [b] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription completed • 0 ms
[2019-02-27 10:29:17:551] [d] FileHistoryTrackerNode(0).onVisibilityChanged — e={"visible":true}
[2019-02-27 10:29:17:551] [e] FileHistoryTrackerNode(0).ensureSubscription
[2019-02-27 10:29:17:551] [f] FileHistoryTrackerNode(0).subscribe
[2019-02-27 10:29:17:551] [10] FileHistoryTrackerNode(0).triggerChange
[2019-02-27 10:29:17:551] [11] FileHistoryView.refreshNode — e=FileHistoryTrackerNode
[2019-02-27 10:29:17:551] [12] FileHistoryTrackerNode(0).refresh — false
[2019-02-27 10:29:17:551] [13] GitUri.fromUri — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx)
[2019-02-27 10:29:17:551] [14] GitService.getRepoPath — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx)
[2019-02-27 10:29:17:551] [15] GitService.getRepository — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx), t={"skipCacheUpdate":true}
[2019-02-27 10:29:17:552] [d] FileHistoryTrackerNode(0).onVisibilityChanged completed • 0 ms
[2019-02-27 10:29:17:552] [16] LineHistoryTrackerNode(0).onVisibilityChanged — e={"visible":true}
[2019-02-27 10:29:17:552] [17] LineHistoryTrackerNode(0).ensureSubscription
[2019-02-27 10:29:17:552] [18] LineHistoryTrackerNode(0).subscribe
[2019-02-27 10:29:17:552] [19] LineHistoryTrackerNode(0).triggerChange
[2019-02-27 10:29:17:552] [1a] LineHistoryView.refreshNode — e=LineHistoryTrackerNode
[2019-02-27 10:29:17:552] [1b] LineHistoryTrackerNode(0).refresh — false
[2019-02-27 10:29:17:552] [1c] GitUri.fromUri — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx)
[2019-02-27 10:29:17:552] [1d] GitService.getRepoPath — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx)
[2019-02-27 10:29:17:552] [1e] GitService.getRepository — e=Uri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx), t={"skipCacheUpdate":true}
[2019-02-27 10:29:17:552] [16] LineHistoryTrackerNode(0).onVisibilityChanged completed • 0 ms
[2019-02-27 10:29:17:552] [1f] RepositoriesNode(0).onVisibilityChanged — e={"visible":true}
[2019-02-27 10:29:17:552] [20] RepositoriesNode(0).ensureSubscription
[2019-02-27 10:29:17:552] [21] RepositoriesNode(0).subscribe
[2019-02-27 10:29:17:553] [22] RepositoriesNode(0).triggerChange
[2019-02-27 10:29:17:553] [23] RepositoriesView.refreshNode — e=RepositoriesNode
[2019-02-27 10:29:17:553] [24] RepositoriesNode(0).refresh — false
[2019-02-27 10:29:17:553] [25] GitService.getOrderedRepositories
[2019-02-27 10:29:17:553] [26] GitService.getRepositories
[2019-02-27 10:29:17:553] [1f] RepositoriesNode(0).onVisibilityChanged completed • 0 ms
[2019-02-27 10:29:17:553] [27] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).onVisibilityChanged — e={"visible":true}
[2019-02-27 10:29:17:553] [28] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription
[2019-02-27 10:29:17:553] [29] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).triggerChange
[2019-02-27 10:29:17:553] [2a] RepositoriesView.refreshNode — e=RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile))
[2019-02-27 10:29:17:553] [2b] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).refresh — false
[2019-02-27 10:29:17:553] [2c] GitService.getStatusForRepo — e=c:/ws/bookedby-react-ui-mobile
[2019-02-27 10:29:17:557] [2d] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription
[2019-02-27 10:29:17:558] [27] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).onVisibilityChanged completed • 4 ms
[2019-02-27 10:29:17:558] [f] FileHistoryTrackerNode(0).subscribe completed • 6 ms
[2019-02-27 10:29:17:558] [18] LineHistoryTrackerNode(0).subscribe completed • 6 ms
[2019-02-27 10:29:17:558] [21] RepositoriesNode(0).subscribe completed • 5 ms
[2019-02-27 10:29:17:558] [28] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription completed • 5 ms
[2019-02-27 10:29:17:559] [2d] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription completed • 1 ms
[2019-02-27 10:29:17:559] [e] FileHistoryTrackerNode(0).ensureSubscription completed • 8 ms
[2019-02-27 10:29:17:559] [17] LineHistoryTrackerNode(0).ensureSubscription completed • 7 ms
[2019-02-27 10:29:17:559] [20] RepositoriesNode(0).ensureSubscription completed • 6 ms
[2019-02-27 10:29:17:559] [26] GitService.getRepositories completed • 6 ms
[2019-02-27 10:29:17:559] [2b] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).refresh completed • 5 ms
[2019-02-27 10:29:17:559] [25] GitService.getOrderedRepositories completed • 6 ms
[2019-02-27 10:29:17:559] [30] RepositoriesView.triggerNodeChange — e=RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile))
[2019-02-27 10:29:17:560] [30] RepositoriesView.triggerNodeChange completed • 0 ms
[2019-02-27 10:29:17:560] [31] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).refresh
[2019-02-27 10:29:17:560] [32] GitService.getStatusForRepo — e=c:/ws/bookedby-react-ui-mobile
[2019-02-27 10:29:17:560] [33] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription
[2019-02-27 10:29:17:560] [34] RepositoriesNode(0).ensureSubscription
[2019-02-27 10:29:17:560] [2a] RepositoriesView.refreshNode completed • 6 ms
[2019-02-27 10:29:17:560] [29] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).triggerChange completed • 6 ms
[2019-02-27 10:29:17:560] [33] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription completed • 0 ms
[2019-02-27 10:29:17:560] [34] RepositoriesNode(0).ensureSubscription completed • 0 ms
[2019-02-27 10:29:17:560] [24] RepositoriesNode(0).refresh completed • 7 ms
[2019-02-27 10:29:17:560] [35] RepositoriesView.triggerNodeChange — e=RepositoriesNode
[2019-02-27 10:29:17:560] [35] RepositoriesView.triggerNodeChange completed • 0 ms
[2019-02-27 10:29:17:560] [31] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).refresh completed • 0 ms
[2019-02-27 10:29:17:560] [23] RepositoriesView.refreshNode completed • 7 ms
[2019-02-27 10:29:17:560] [22] RepositoriesNode(0).triggerChange completed • 7 ms
[2019-02-27 10:29:17:561] [c:/ws/bookedby-react-ui-mobile] git ls-files -- c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx • 76 ms 
[2019-02-27 10:29:17:561] [a] GitService.isTracked returned true • 76 ms — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:17:561] [2e] GitService.isTracked returned true • 2 ms — e=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx, t=c:/ws/bookedby-react-ui-mobile, i={"skipCacheUpdate":true}
[2019-02-27 10:29:17:561] [2f] GitService.isTracked returned true • 2 ms — e=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx, t=c:/ws/bookedby-react-ui-mobile, i={"skipCacheUpdate":true}
[2019-02-27 10:29:17:561] [15] GitService.getRepository returned c:/ws/bookedby-react-ui-mobile • 9 ms
[2019-02-27 10:29:17:561] [1e] GitService.getRepository returned c:/ws/bookedby-react-ui-mobile • 9 ms
[2019-02-27 10:29:17:561] [14] GitService.getRepoPath returned c:/ws/bookedby-react-ui-mobile • 9 ms
[2019-02-27 10:29:17:561] [1d] GitService.getRepoPath returned c:/ws/bookedby-react-ui-mobile • 9 ms
[2019-02-27 10:29:17:561] [13] GitUri.fromUri returned GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile) • 10 ms
[2019-02-27 10:29:17:562] [1c] GitUri.fromUri returned GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile) • 9 ms
[2019-02-27 10:29:17:562] [36] FileHistoryTrackerNode(0).resetChild
[2019-02-27 10:29:17:562] [36] FileHistoryTrackerNode(0).resetChild completed • 0 ms
[2019-02-27 10:29:17:562] [37] LineHistoryTrackerNode(0).resetChild
[2019-02-27 10:29:17:562] [37] LineHistoryTrackerNode(0).resetChild completed • 0 ms
[2019-02-27 10:29:17:562] [12] FileHistoryTrackerNode(0).refresh returned false, uri=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile) • 10 ms
[2019-02-27 10:29:17:562] [1b] LineHistoryTrackerNode(0).refresh completed, uri=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile) • 9 ms
[2019-02-27 10:29:17:562] [38] FileHistoryView.triggerNodeChange — e=FileHistoryTrackerNode
[2019-02-27 10:29:17:562] [38] FileHistoryView.triggerNodeChange completed • 0 ms
[2019-02-27 10:29:17:562] [39] LineHistoryView.triggerNodeChange — e=LineHistoryTrackerNode
[2019-02-27 10:29:17:562] [39] LineHistoryView.triggerNodeChange completed • 0 ms
[2019-02-27 10:29:17:562] [11] FileHistoryView.refreshNode completed • 11 ms
[2019-02-27 10:29:17:562] [10] FileHistoryTrackerNode(0).triggerChange completed • 11 ms
[2019-02-27 10:29:17:562] [1a] LineHistoryView.refreshNode completed • 10 ms
[2019-02-27 10:29:17:562] [19] LineHistoryTrackerNode(0).triggerChange completed • 10 ms
[2019-02-27 10:29:17:562] [3a] GitService.getBlameForLine — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile), t=127
[2019-02-27 10:29:17:563] [3b] GitService.getBlameForFile — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:17:563] [3c] GitService.getBlameForFile — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:17:563] [3b] GitService.getBlameForFile Cache miss: 'blame'
[2019-02-27 10:29:17:563] [3b] GitService.getBlameForFile Cache add: 'blame'
[2019-02-27 10:29:17:563] [3c] GitService.getBlameForFile Cache hit: 'blame'
[2019-02-27 10:29:17:563] [3d] GitService.isTracked returned true • 0 ms — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:17:678] [c:/ws/bookedby-react-ui-mobile] git blame --root --incremental -- src/Modals/DDatePicker/index.tsx • 114 ms 
[2019-02-27 10:29:17:679] [3e] GitService.getCurrentUser — e=c:/ws/bookedby-react-ui-mobile
[2019-02-27 10:29:17:710] [c:/ws/bookedby-react-ui-mobile] git status --porcelain=v2 --branch -u • 156 ms 
[2019-02-27 10:29:17:710] [c:/ws/bookedby-react-ui-mobile] git status --porcelain=v2 --branch -u • 150 ms (await) 
[2019-02-27 10:29:17:710] [2c] GitService.getStatusForRepo completed • 157 ms
[2019-02-27 10:29:17:711] [32] GitService.getStatusForRepo completed • 150 ms
[2019-02-27 10:29:17:775] [c:/ws/bookedby-react-ui-mobile] git config --get-regex user.(name|email) • 96 ms 
[2019-02-27 10:29:17:842] [3f] FileHistoryNode(0).ensureSubscription
[2019-02-27 10:29:17:842] [40] FileHistoryNode(0).subscribe
[2019-02-27 10:29:17:842] [41] GitService.getRepository — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:17:842] [42] LineHistoryNode(0).ensureSubscription
[2019-02-27 10:29:17:842] [43] LineHistoryNode(0).subscribe
[2019-02-27 10:29:17:842] [44] GitService.getRepository — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:17:842] [41] GitService.getRepository returned c:/ws/bookedby-react-ui-mobile • 0 ms
[2019-02-27 10:29:17:842] [44] GitService.getRepository returned c:/ws/bookedby-react-ui-mobile • 0 ms
[2019-02-27 10:29:17:843] [40] FileHistoryNode(0).subscribe completed • 0 ms
[2019-02-27 10:29:17:843] [43] LineHistoryNode(0).subscribe completed • 0 ms
[2019-02-27 10:29:17:843] [3f] FileHistoryNode(0).ensureSubscription completed • 0 ms
[2019-02-27 10:29:17:843] [42] LineHistoryNode(0).ensureSubscription completed • 0 ms
[2019-02-27 10:29:17:843] [45] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription
[2019-02-27 10:29:17:843] [45] RepositoryNode(0:gitlens:repository(c:/ws/bookedby-react-ui-mobile)).ensureSubscription completed • 0 ms
[2019-02-27 10:29:17:853] [46] GitService.getStatusForFile — e=c:/ws/bookedby-react-ui-mobile, t=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx
[2019-02-27 10:29:17:857] [47] GitService.getLogForFile — e=c:/ws/bookedby-react-ui-mobile, t=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx, i={"range":{"start":{"line":127,"character":9},"end":{"line":127,"character":9},"active":{"line":127,"character":9},"anchor":{"line":127,"character":9}}}
[2019-02-27 10:29:17:858] [48] GitService.isTracked returned true • 0 ms — e=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx, t=c:/ws/bookedby-react-ui-mobile, i={}
[2019-02-27 10:29:17:865] [c:/ws/bookedby-react-ui-mobile] git check-mailmap Alexey Gurianov <alexey.gurianov@salonultimate.com> • 89 ms 
[2019-02-27 10:29:17:865] [3e] GitService.getCurrentUser completed • 186 ms
[2019-02-27 10:29:17:867] [3b] GitService.getBlameForFile completed • 304 ms
[2019-02-27 10:29:17:867] [3c] GitService.getBlameForFile completed • 303 ms
[2019-02-27 10:29:17:867] [3a] GitService.getBlameForLine completed • 304 ms
[2019-02-27 10:29:17:937] [c:/ws/bookedby-react-ui-mobile] git status --porcelain=v2 -- src/Modals/DDatePicker/index.tsx • 84 ms 
[2019-02-27 10:29:17:937] [46] GitService.getStatusForFile completed • 84 ms
[2019-02-27 10:29:17:937] [49] GitService.getLogForFile — e=c:/ws/bookedby-react-ui-mobile, t=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx, i={}
[2019-02-27 10:29:17:937] [49] GitService.getLogForFile Cache miss: 'log:follow'
[2019-02-27 10:29:17:937] [49] GitService.getLogForFile Cache add: 'log:follow'
[2019-02-27 10:29:17:938] [4a] GitService.isTracked returned true • 0 ms — e=c:\ws\bookedby-react-ui-mobile\src\Modals\DDatePicker\index.tsx, t=c:/ws/bookedby-react-ui-mobile, i={}
[2019-02-27 10:29:18:013] [c:/ws/bookedby-react-ui-mobile] git log --name-status --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e -m -n200 --follow -L 128,128:src/Modals/DDatePicker/index.tsx -- src/Modals/DDatePicker/index.tsx • 155 ms 
[2019-02-27 10:29:18:013] [4b] GitService.getCurrentUser — e=c:/ws/bookedby-react-ui-mobile
[2019-02-27 10:29:18:013] [4b] GitService.getCurrentUser completed • 0 ms
[2019-02-27 10:29:18:014] [47] GitService.getLogForFile completed • 156 ms
[2019-02-27 10:29:18:014] [4c] GitService.getBlameForLine — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile), t=127
[2019-02-27 10:29:18:014] [4d] GitService.getBlameForFile — e=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile)
[2019-02-27 10:29:18:014] [4d] GitService.getBlameForFile Cache hit: 'blame'
[2019-02-27 10:29:18:014] [4d] GitService.getBlameForFile completed • 0 ms
[2019-02-27 10:29:18:014] [4c] GitService.getBlameForLine completed • 0 ms
[2019-02-27 10:29:18:117] [4e] LineHistoryTrackerNode(0).onActiveLinesChanged
[2019-02-27 10:29:18:118] [4f] LineHistoryTrackerNode(0).triggerChange
[2019-02-27 10:29:18:118] [50] LineHistoryView.refreshNode — e=LineHistoryTrackerNode
[2019-02-27 10:29:18:118] [51] LineHistoryTrackerNode(0).refresh — false
[2019-02-27 10:29:18:118] [4e] LineHistoryTrackerNode(0).onActiveLinesChanged completed • 0 ms
[2019-02-27 10:29:18:118] [51] LineHistoryTrackerNode(0).refresh completed, uri=GitUri(file:///c:/ws/bookedby-react-ui-mobile/src/Modals/DDatePicker/index.tsx repoPath=c:/ws/bookedby-react-ui-mobile) • 0 ms
[2019-02-27 10:29:18:118] [50] LineHistoryView.refreshNode completed • 0 ms
[2019-02-27 10:29:18:118] [4f] LineHistoryTrackerNode(0).triggerChange completed • 0 ms
[2019-02-27 10:29:18:131] [c:/ws/bookedby-react-ui-mobile] git log --name-status --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e -m -n200 --follow -- src/Modals/DDatePicker/index.tsx • 193 ms 
[2019-02-27 10:29:18:131] [52] GitService.getCurrentUser — e=c:/ws/bookedby-react-ui-mobile
[2019-02-27 10:29:18:131] [52] GitService.getCurrentUser completed • 0 ms
[2019-02-27 10:29:18:132] [49] GitService.getLogForFile completed • 195 ms
[2019-02-27 10:29:24:120] GitCodeLensProvider.provideCodeLenses: — 8 symbol(s) found
[2019-02-27 10:29:49:033] [53] FileHistoryTrackerNode(0).onActiveEditorChanged
[2019-02-27 10:29:49:033] [54] FileHistoryTrackerNode(0).triggerChange
[2019-02-27 10:29:49:033] [55] FileHistoryView.refreshNode — e=FileHistoryTrackerNode
[2019-02-27 10:29:49:033] [56] FileHistoryTrackerNode(0).refresh — false
[2019-02-27 10:29:49:033] [53] FileHistoryTrackerNode(0).onActiveEditorChanged completed • 0 ms
[2019-02-27 10:29:49:034] [57] RepositoriesNode(0).onActiveEditorChanged
[2019-02-27 10:29:49:034] [57] RepositoriesNode(0).onActiveEditorChanged completed • 0 ms
[2019-02-27 10:29:49:034] [56] FileHistoryTrackerNode(0).refresh returned true • 0 ms
[2019-02-27 10:29:49:034] [55] FileHistoryView.refreshNode completed • 1 ms
[2019-02-27 10:29:49:035] [54] FileHistoryTrackerNode(0).triggerChange completed • 1 ms

```

**Comment by Guria** [comment]
Just found out that in my case it conflicting with another extension:
```
Name: Render CRLF
Id: medo64.render-crlf
Description: Displays LF/CR/CRLF line ending (aka end-of-line, EOL) symbols when Render whitespace is turned on.
Version: 1.3.0
Publisher: Josip Medved
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=medo64.render-crlf
```

**Comment by eamodio** [comment]
@Guria Ah, glad you found the issue and that it is resolved.

I'm going to close this issue for now, until there is more information pointing to an issue. Thanks!

**Comment by gservat** [comment]
Just in case it helps anyone... in my case :man_facepalming: the file I was looking at was [git-crypted](https://github.com/AGWA/git-crypt). The blame works fine for a non-encrypted file.

**Comment by rohansekhri** [comment]
[This bug](https://github.com/microsoft/vscode/issues/90611) is still reproducible. I have opened it with VSCode repo as I feel it is more relevant there. Recording it here since it affects both gitlens and vscode's gutters at the same time. 

No extensions except gitlens were installed.

**Comment by eamodio** [comment]
@rohansekhri Could you be running into: microsoft/vscode#12448? Are you using 10.2.1?

**Comment by rohansekhri** [comment]
@eamodio [My bug](https://github.com/microsoft/vscode/issues/90611) is a subset of this one. The real cause is actually the case-(in)sensitivity of VSCode. Please ignore my comments above. It is not a GitLens issue. By the way, if you are interested in logs for GitLens to do any enhancements, I have posted them in my bug. Thanks
