### ISSUE TITLE
"Open Revision" does not work with RemoteSSH

### ISSUE THREAD

**Issue by anatolyburakov** [eamodio/vscode-gitlens#857]
Issue Type: <b>Bug</b>

1. Use VSCode Insiders build
2. Use RemoteSSH Insiders version
3. Use GitLens
4. Open any file
5. Switch to GitLens
6. Pick any past commit
7. Right-click and select "Open revision"

Result: 
Error running command gitlens.views.openFileRevision: Running the contributed command: 'gitlens.views.openFileRevision' failed.. This is likely caused by the extension that contributes gitlens.views.openFileRevision.

Extension version: 9.9.3
VS Code version: Code - Insiders 1.39.0-insider (575062278d181c075ea8dce345ab3d20a127309c, 2019-09-20T06:11:13.647Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.1.3-050103-generic
Remote OS version: Linux x64 5.1.3-050103-generic
Remote OS version: Linux x64 5.2.14-050214-generic

**Comment by eamodio** [comment]
This should be fixed in GitLens 10

**Comment by anatolyburakov** [comment]
This is not fixed as far as i can tell - i'm running GitLens 10.0.0 with latest insiders build, and i'm still seeing the issue.

**Comment by anatolyburakov** [comment]
@eamodio never mind, updating to latest Insiders build fixed the issue. all seems to be working now, thanks!
