### ISSUE TITLE
Open Changes with Previous Version broken?

### ISSUE THREAD

**Issue by chadbr** [eamodio/vscode-gitlens#945]
GitLens Version: 10.2.0

VSCode version:
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Press the `Open Changes with Previous Version` button - always gives blank files for previous.
![image](https://user-images.githubusercontent.com/3179452/73983945-2ef5ae00-48fd-11ea-8c26-125a7eb1caed.png)

![image](https://user-images.githubusercontent.com/3179452/73984594-9f50ff00-48fe-11ea-8f68-70e3fae26b54.png)

Clear errors below in Gitlens git output - but I have no idea why?

Thanks, Chad

Gitlens
```
[2020-02-06 22:28:36:830] [23e] GitUri.fromUri — e=Uri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:36:830] [23f] GitService.getRepoPath — e=Uri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:36:830] [240] GitService.getRepository — e=Uri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts), t={"skipCacheUpdate":true}
[2020-02-06 22:28:36:830] [240] GitService.getRepository returned undefined • 0 ms
[2020-02-06 22:28:36:830] [241] GitService.getRepoPathCore — e=c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts, t=false
[2020-02-06 22:28:36:885] [c:\dev\vsts\kinetix-backend\src\integration\udl] git rev-parse --show-toplevel • 55 ms 
[2020-02-06 22:28:36:886] [241] GitService.getRepoPathCore completed • 55 ms
[2020-02-06 22:28:36:886] [23f] GitService.getRepoPath returned C:/dev/vsts/kinetix-backend • 55 ms
[2020-02-06 22:28:36:886] [23e] GitUri.fromUri returned GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend) • 55 ms
[2020-02-06 22:28:36:886] [242] GitService.getPreviousDiffUris — e=C:/dev/vsts/kinetix-backend, t=GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend), i=undefined, o=0
[2020-02-06 22:28:36:886] [243] GitService.getStatusForFile — e=C:/dev/vsts/kinetix-backend, t=src/integration/udl/udl.router.ts
[2020-02-06 22:28:36:958] [C:/dev/vsts/kinetix-backend] git status --porcelain=v2 --find-renames -- src/integration/udl/udl.router.ts • 71 ms 
[2020-02-06 22:28:36:958] [245] GitStatusParser.parseV2 completed • 0 ms
[2020-02-06 22:28:36:958] [244] GitStatusParser.parse completed • 0 ms
[2020-02-06 22:28:36:958] [243] GitService.getStatusForFile completed • 72 ms
[2020-02-06 22:28:36:958] [246] GitService.getPreviousUri — e=C:/dev/vsts/kinetix-backend, t=GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend), i=undefined, o=0, r=undefined, n=false
[2020-02-06 22:28:37:018] [C:/dev/vsts/kinetix-backend] git log --format=%x3cr%x3e%x20%H -n2 --follow --name-status -- src/integration/udl/udl.router.ts • 59 ms 
[2020-02-06 22:28:37:018] [247] GitLogParser.parseSimple
[2020-02-06 22:28:37:018] [247] GitLogParser.parseSimple completed • 0 ms
[2020-02-06 22:28:37:018] [246] GitService.getPreviousUri completed • 60 ms
[2020-02-06 22:28:37:018] [242] GitService.getPreviousDiffUris completed • 132 ms
[2020-02-06 22:28:37:019] [248] GitService.resolveReference — e=C:/dev/vsts/kinetix-backend, t=bc0389bbaac3fd331391b9c7a471f845966c1d96, i=Uri(file:///c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:37:073] [C:/dev/vsts/kinetix-backend] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false cat-file -e bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • Not a valid object name bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • 54 ms 
[2020-02-06 22:28:37:073] [248] GitService.resolveReference completed • 54 ms
[2020-02-06 22:28:37:074] [249] GitService.resolveReference — e=C:/dev/vsts/kinetix-backend, t=, i=Uri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:37:074] [249] GitService.resolveReference completed • 0 ms
[2020-02-06 22:28:37:074] [24a] GitService.getVersionedUri — e=C:/dev/vsts/kinetix-backend, t=c:\dev\vsts\kinetix-backend\c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts, i=0000000000000000000000000000000000000000-
[2020-02-06 22:28:37:074] [24b] GitService.getVersionedUri — e=C:/dev/vsts/kinetix-backend, t=c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts, i=
[2020-02-06 22:28:37:079] [24a] GitService.getVersionedUri completed • 5 ms
[2020-02-06 22:28:37:128] [C:/dev/vsts/kinetix-backend] git ls-files -- c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts • 54 ms 
[2020-02-06 22:28:37:129] [24b] GitService.getVersionedUri completed • 55 ms
[2020-02-06 22:28:37:149] [24c] GitFileSystemProvider.readFile — e=Uri(gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"})
[2020-02-06 22:28:37:149] [24d] GitFileSystemProvider.stat — e=Uri(gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"})
[2020-02-06 22:28:37:149] [24c] GitFileSystemProvider.readFile completed • 0 ms
[2020-02-06 22:28:37:149] [24d] GitFileSystemProvider.stat completed • 0 ms
[2020-02-06 22:28:37:149] [24e] LineAnnotationController.onActiveLinesChanged — e=editor=undefined, lines=undefined, pending=false, reason=editor
[2020-02-06 22:28:37:149] [24f] LineAnnotationController.clear completed • 0 ms
[2020-02-06 22:28:37:149] [24e] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:149] [250] LineHoverController.onActiveLinesChanged — e=editor=undefined, lines=undefined, pending=false, reason=editor
[2020-02-06 22:28:37:150] [250] LineHoverController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:150] [251] StatusBarController.onActiveLinesChanged — e=editor=undefined, lines=undefined, pending=false, reason=editor
[2020-02-06 22:28:37:150] [251] StatusBarController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:184] [252] LineAnnotationController.onActiveLinesChanged — e=editor=file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts, lines=undefined, pending=true, reason=selection
[2020-02-06 22:28:37:184] [253] LineAnnotationController.clear completed • 0 ms
[2020-02-06 22:28:37:184] [252] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:184] [254] LineHoverController.onActiveLinesChanged — e=editor=file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts, lines=undefined, pending=true, reason=selection
[2020-02-06 22:28:37:184] [254] LineHoverController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:184] [255] StatusBarController.onActiveLinesChanged — e=editor=file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts, lines=undefined, pending=true, reason=selection
[2020-02-06 22:28:37:184] [255] StatusBarController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:434] [256] GitService.getBlameForLine — e=GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend), t=286
[2020-02-06 22:28:37:435] [257] GitService.getBlameForFile — e=GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend)
[2020-02-06 22:28:37:435] [257] GitService.getBlameForFile Cache hit: 'blame'
[2020-02-06 22:28:37:435] [257] GitService.getBlameForFile completed • 0 ms
[2020-02-06 22:28:37:435] [256] GitService.getBlameForLine completed • 0 ms
[2020-02-06 22:28:37:435] [258] LineAnnotationController.onActiveLinesChanged — e=editor=file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts, lines=286, pending=false, reason=selection
[2020-02-06 22:28:37:435] [259] LineAnnotationController.refresh
[2020-02-06 22:28:37:435] [25a] LineAnnotationController.clear completed • 0 ms
[2020-02-06 22:28:37:435] [258] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:435] [25b] LineHoverController.onActiveLinesChanged — e=editor=file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts, lines=286, pending=false, reason=selection
[2020-02-06 22:28:37:435] [25b] LineHoverController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:435] [25c] StatusBarController.onActiveLinesChanged — e=editor=file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts, lines=286, pending=false, reason=selection
[2020-02-06 22:28:37:435] [25c] StatusBarController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:37:435] [259] LineAnnotationController.refresh completed • line(s)=286 • 0 ms
[2020-02-06 22:28:40:456] [25d] GitUri.fromUri — e=Uri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:40:456] [25e] GitService.getRepoPath — e=Uri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:40:456] [25f] GitService.getRepository — e=Uri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts), t={"skipCacheUpdate":true}
[2020-02-06 22:28:40:456] [25f] GitService.getRepository returned undefined • 0 ms
[2020-02-06 22:28:40:456] [260] GitService.getRepoPathCore — e=c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts, t=false
[2020-02-06 22:28:40:522] [c:\dev\vsts\kinetix-backend\src\integration\udl] git rev-parse --show-toplevel • 65 ms 
[2020-02-06 22:28:40:523] [260] GitService.getRepoPathCore completed • 66 ms
[2020-02-06 22:28:40:523] [25e] GitService.getRepoPath returned C:/dev/vsts/kinetix-backend • 66 ms
[2020-02-06 22:28:40:523] [25d] GitUri.fromUri returned GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend) • 66 ms
[2020-02-06 22:28:40:523] [261] GitService.getPreviousDiffUris — e=C:/dev/vsts/kinetix-backend, t=GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend), i=undefined, o=1
[2020-02-06 22:28:40:523] [262] GitService.getStatusForFile — e=C:/dev/vsts/kinetix-backend, t=src/integration/udl/udl.router.ts
[2020-02-06 22:28:40:584] [C:/dev/vsts/kinetix-backend] git status --porcelain=v2 --find-renames -- src/integration/udl/udl.router.ts • 61 ms 
[2020-02-06 22:28:40:584] [264] GitStatusParser.parseV2 completed • 0 ms
[2020-02-06 22:28:40:584] [263] GitStatusParser.parse completed • 0 ms
[2020-02-06 22:28:40:585] [262] GitService.getStatusForFile completed • 61 ms
[2020-02-06 22:28:40:585] [265] GitService.getPreviousUri — e=C:/dev/vsts/kinetix-backend, t=GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend), i=undefined, o=0, r=undefined, n=false
[2020-02-06 22:28:40:645] [C:/dev/vsts/kinetix-backend] git log --format=%x3cr%x3e%x20%H -n2 --follow --name-status -- src/integration/udl/udl.router.ts • 60 ms 
[2020-02-06 22:28:40:645] [266] GitLogParser.parseSimple
[2020-02-06 22:28:40:645] [266] GitLogParser.parseSimple completed • 0 ms
[2020-02-06 22:28:40:645] [265] GitService.getPreviousUri completed • 60 ms
[2020-02-06 22:28:40:645] [267] GitService.getPreviousUri — e=C:/dev/vsts/kinetix-backend, t=GitUri(file:///c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts repoPath=C:/dev/vsts/kinetix-backend), i=undefined, o=1, r=undefined, n=false
[2020-02-06 22:28:40:695] [C:/dev/vsts/kinetix-backend] git log --format=%x3cr%x3e%x20%H -n3 --follow --name-status -- src/integration/udl/udl.router.ts • 50 ms 
[2020-02-06 22:28:40:696] [268] GitLogParser.parseSimple
[2020-02-06 22:28:40:696] [268] GitLogParser.parseSimple completed • 0 ms
[2020-02-06 22:28:40:696] [267] GitService.getPreviousUri completed • 50 ms
[2020-02-06 22:28:40:696] [261] GitService.getPreviousDiffUris completed • 173 ms
[2020-02-06 22:28:40:696] [269] GitService.resolveReference — e=C:/dev/vsts/kinetix-backend, t=69ab31be12f3f15b6ad06cad2c65c691cad18a38, i=Uri(file:///c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:40:743] [C:/dev/vsts/kinetix-backend] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false cat-file -e 69ab31be12f3f15b6ad06cad2c65c691cad18a38:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • Not a valid object name 69ab31be12f3f15b6ad06cad2c65c691cad18a38:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • 46 ms 
[2020-02-06 22:28:40:743] [269] GitService.resolveReference completed • 46 ms
[2020-02-06 22:28:40:743] [26a] GitService.resolveReference — e=C:/dev/vsts/kinetix-backend, t=bc0389bbaac3fd331391b9c7a471f845966c1d96, i=Uri(file:///c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts)
[2020-02-06 22:28:40:794] [C:/dev/vsts/kinetix-backend] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false cat-file -e bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • Not a valid object name bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • 51 ms 
[2020-02-06 22:28:40:795] [26a] GitService.resolveReference completed • 51 ms
[2020-02-06 22:28:40:795] [26b] GitService.getVersionedUri — e=C:/dev/vsts/kinetix-backend, t=c:\dev\vsts\kinetix-backend\c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts, i=0000000000000000000000000000000000000000-
[2020-02-06 22:28:40:795] [26c] GitService.getVersionedUri — e=C:/dev/vsts/kinetix-backend, t=c:\dev\vsts\kinetix-backend\c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts, i=0000000000000000000000000000000000000000-
[2020-02-06 22:28:40:795] [26b] GitService.getVersionedUri completed • 0 ms
[2020-02-06 22:28:40:795] [26c] GitService.getVersionedUri completed • 0 ms
[2020-02-06 22:28:40:835] [26d] GitFileSystemProvider.stat — e=Uri(gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"})
[2020-02-06 22:28:40:836] [26e] GitUri.fromUri — e=Uri(gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"})
[2020-02-06 22:28:40:837] [26d] GitFileSystemProvider.stat completed • 1 ms
[2020-02-06 22:28:40:837] [26e] GitUri.fromUri returned GitUri(gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"} repoPath=C:/dev/vsts/kinetix-backend sha=0000000000000000000000000000000000000000-) • 0 ms
[2020-02-06 22:28:40:837] [26f] GitService.getRepository — e=GitUri(gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"} repoPath=C:/dev/vsts/kinetix-backend sha=0000000000000000000000000000000000000000-)
[2020-02-06 22:28:40:837] [26f] GitService.getRepository returned C:/dev/vsts/kinetix-backend • 0 ms
[2020-02-06 22:28:40:837] [270] GitService.isTracked returned false • 0 ms — e=GitUri(gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"} repoPath=C:/dev/vsts/kinetix-backend sha=0000000000000000000000000000000000000000-)
[2020-02-06 22:28:40:837] [271] LineAnnotationController.onActiveLinesChanged — e=editor=gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"}, lines=undefined, pending=true, reason=editor
[2020-02-06 22:28:40:838] [272] LineAnnotationController.clear completed • 0 ms
[2020-02-06 22:28:40:838] [271] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:40:838] [273] LineHoverController.onActiveLinesChanged — e=editor=gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"}, lines=undefined, pending=true, reason=editor
[2020-02-06 22:28:40:838] [273] LineHoverController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:40:838] [274] StatusBarController.onActiveLinesChanged — e=editor=gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"}, lines=undefined, pending=true, reason=editor
[2020-02-06 22:28:40:838] [274] StatusBarController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:41:090] [275] LineAnnotationController.onActiveLinesChanged — e=editor=gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"}, lines=undefined, pending=false, reason=editor
[2020-02-06 22:28:41:090] [276] LineAnnotationController.clear completed • 0 ms
[2020-02-06 22:28:41:090] [275] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:41:090] [277] LineHoverController.onActiveLinesChanged — e=editor=gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"}, lines=undefined, pending=false, reason=editor
[2020-02-06 22:28:41:090] [277] LineHoverController.onActiveLinesChanged completed • 0 ms
[2020-02-06 22:28:41:090] [278] StatusBarController.onActiveLinesChanged — e=editor=gitlens://(deleted)/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts?{"path":"/c:/dev/vsts/kinetix-backend/c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts","ref":"0000000000000000000000000000000000000000-","repoPath":"C:/dev/vsts/kinetix-backend"}, lines=undefined, pending=false, reason=editor
[2020-02-06 22:28:41:090] [278] StatusBarController.onActiveLinesChanged completed • 0 ms

```

Gitlens.git
```
[2020-02-06 22:27:41:754] [c:\dev\vsts\kinetix-backend\src\integration\udl] git rev-parse --show-toplevel • 62 ms 
[2020-02-06 22:27:41:813] [C:/dev/vsts/kinetix-backend] git status --porcelain=v2 --find-renames -- src/integration/udl/udl.router.ts • 58 ms 
[2020-02-06 22:27:41:873] [C:/dev/vsts/kinetix-backend] git log --format=%x3cr%x3e%x20%H -n2 --follow --name-status -- src/integration/udl/udl.router.ts • 59 ms 
[2020-02-06 22:27:41:917] [C:/dev/vsts/kinetix-backend] git cat-file -e bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • FAILED 44 ms 

Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false cat-file -e bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts
fatal: Not a valid object name bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts

[2020-02-06 22:27:41:962] [C:/dev/vsts/kinetix-backend] git ls-files -- c:\dev\vsts\kinetix-backend\src\integration\udl\udl.router.ts • 44 ms 
[2020-02-06 22:27:44:498] [c:\dev\vsts\kinetix-backend\src\integration\udl] git rev-parse --show-toplevel • 56 ms 
[2020-02-06 22:27:44:552] [C:/dev/vsts/kinetix-backend] git status --porcelain=v2 --find-renames -- src/integration/udl/udl.router.ts • 53 ms 
[2020-02-06 22:27:44:609] [C:/dev/vsts/kinetix-backend] git log --format=%x3cr%x3e%x20%H -n2 --follow --name-status -- src/integration/udl/udl.router.ts • 56 ms 
[2020-02-06 22:27:44:659] [C:/dev/vsts/kinetix-backend] git log --format=%x3cr%x3e%x20%H -n3 --follow --name-status -- src/integration/udl/udl.router.ts • 49 ms 
[2020-02-06 22:27:44:701] [C:/dev/vsts/kinetix-backend] git cat-file -e 69ab31be12f3f15b6ad06cad2c65c691cad18a38:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • FAILED 41 ms 

Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false cat-file -e 69ab31be12f3f15b6ad06cad2c65c691cad18a38:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts
fatal: Not a valid object name 69ab31be12f3f15b6ad06cad2c65c691cad18a38:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts

[2020-02-06 22:27:44:745] [C:/dev/vsts/kinetix-backend] git cat-file -e bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts • FAILED 43 ms 

Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false cat-file -e bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts
fatal: Not a valid object name bc0389bbaac3fd331391b9c7a471f845966c1d96:./c:/dev/vsts/kinetix-backend/src/integration/udl/udl.router.ts


```

**Comment by firmantr3** [comment]
i got same problem

**Comment by pookdeveloper** [comment]
The same for me, for now I can use timeline in the last version of vscode (1.42)

**Comment by michaelmarcuccio** [comment]
this occurs for me as well. It slows down dev speed without this functionality

**Comment by jjasoncool** [comment]
I have found that I install git older release, the issue is fixed.
So I don't know is the broken reason is git version or vscode version or gitlens update.

https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/Git-2.23.0-64-bit.exe

**Comment by eamodio** [comment]
Are you all using Git 2.25?

**Comment by chadbr** [comment]
```
C:\Users\chadbr>git --version
git version 2.25.0.windows.1  
```

**Comment by eamodio** [comment]
I believe this is fixed in 10.2.1 which I just released.

**Comment by steffencircle** [comment]
Hi,

just came here after i noticed that "compare with previous revision" isn't working anymore.
However i am afraid it is still not fixed for me although i am using 10.2.1

For what is worth i have open my git repo from a Network drive which is a mapped CIFS Share.

**Comment by chadbr** [comment]
10.2.1 working for me...
